import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";
import { stageRelease } from "../tools/stage-release.mjs";
test("deployment stages committed manifest inputs without ignored notes or working-tree edits", (t) => {
  const root = mkdtempSync(join(tmpdir(), "todo-release-test-"));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const repo = join(root, "repo");
  mkdirSync(repo);
  mkdirSync(join(repo, "tools"));
  mkdirSync(join(repo, "src"));
  writeFileSync(join(repo, "tools/deploy-source.txt"), "src\n");
  writeFileSync(join(repo, "src/app.js"), "committed");
  const git = (...args) => execFileSync("git", args, { cwd: repo, stdio: "pipe" });
  git("init", "-q");
  git("add", ".");
  git("-c", "user.name=Test", "-c", "user.email=test@example.invalid", "commit", "-qm", "fixture");
  writeFileSync(join(repo, "src/app.js"), "uncommitted");
  writeFileSync(join(repo, "src/ignored.txt"), "not committed");
  writeFileSync(join(repo, "local-notes.md"), "private");
  const destination = join(root, "release");
  const revision = stageRelease(repo, destination);
  assert.equal(readFileSync(join(destination, "src/app.js"), "utf8"), "committed");
  assert.equal(existsSync(join(destination, "src/ignored.txt")), false);
  assert.equal(existsSync(join(destination, "local-notes.md")), false);
  assert.equal(readFileSync(join(destination, "REVISION"), "utf8"), revision + "\n");
});
